eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
    register-with-eureka: false
    fetch-registry: false  
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0  

ead:
  serviceRegistry:
    username: serviceregistry
    password: ead123sr    