server:
  port: ${PORT}

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authuser-service
              uri: lb://EAD-AUTHUSER-SERVICE
              predicates:
                - Path=/ead-authuser/**
              filters:
                - StripPrefix=1

            - id: course-service
              uri: lb://EAD-COURSE-SERVICE
              predicates:
                - Path=/ead-course/**
              filters:
                - StripPrefix=1
            - id: notification-service
              uri: lb://EAD-NOTIFICATION-SERVICE
              predicates:
                - Path=/ead-notification/**
              filters:
                - StripPrefix=1
          discovery:
            locator:
              enabled: true  # Ativando o Discovery Locator
